
import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';

const app = express();
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Cloud Run sets the PORT environment variable. Default to 8080 for local testing.
const port = parseInt(process.env.PORT) || 8080;

// Serve static files from the 'dist' directory generated by 'npm run build'
app.use(express.static(path.join(__dirname, 'dist')));

// Handle client-side routing by returning index.html for all non-static requests
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

app.listen(port, () => {
  console.log(`Server is running and listening on port ${port}`);
});
